"""
Generate one bot config per Ally slot.

RLBot groups cars by `agent_id`. Every car sharing an id is handed to a single
process, which the framework expects to be a hivemind driving all of them. Our
`Bot` base class only drives `controllables[0]`, so putting six cars in a match
that all declare `agent_id = "joe/ally"` leaves one car per team moving and the
rest parked -- which looks like a 3v1.

Each slot therefore needs its own agent id and its own process. That also keeps
the peer-comms design meaningful: separate processes have something to
negotiate, whereas a hivemind would just share memory.

    python tools/gen_ally_slots.py [count]

Regenerates bot/ally-N.bot.toml for N in 1..count (default 6).
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BOT_DIR = ROOT / "bot"

# Single-quoted TOML literal strings: backslashes are not escape sequences,
# which is what a Windows path needs.
WINDOWS_CMD = r"..\venv\Scripts\python.exe ally.py"
LINUX_CMD = "../venv/bin/python ally.py"

TEMPLATE = """#:schema https://rlbot.org/schemas/agent.json
# Ally instance {n} of {total}.
#
# Generated by tools/gen_ally_slots.py -- edit that, not this file.
#
# Each Ally slot needs a distinct agent_id. RLBot hands every car sharing an id
# to one process as a hivemind, and our Bot base class only drives the first
# controllable, so duplicate ids leave cars parked on the pitch.
[settings]
agent_id = "joe/ally-{n}"
name = "Ally {n}"
loadout_file = "loadout.toml"
root_dir = ""
run_command = '{win}'
run_command_linux = "{lin}"

[details]
description = "An adaptive teammate that learns how you play and covers for it."
fun_fact = "Coordinates with other Allies over match comms and pools calibration."
developer = "Joe"
language = "Python 3"
tags = ["teamplay"]
"""


def main() -> int:
    total = 6
    if len(sys.argv) > 1:
        try:
            total = max(1, min(int(sys.argv[1]), 8))
        except ValueError:
            print(f"bad count {sys.argv[1]!r}")
            return 1

    for n in range(1, total + 1):
        path = BOT_DIR / f"ally-{n}.bot.toml"
        path.write_text(
            TEMPLATE.format(n=n, total=total, win=WINDOWS_CMD, lin=LINUX_CMD),
            encoding="utf-8",
        )
        print(f"wrote {path.relative_to(ROOT)}  (agent_id joe/ally-{n})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
